### ISSUE TITLE
セクション設定画面追加

### ISSUE THREAD

**Issue by a-tak** [a-tak/taskclear#64]

**Comment by a-tak** [comment]
* router使って別viewにする
* コンポーネントの差し替えで表現し続けるのは状態維持がつらい
* でもログイン状態の管理は活かしておきたいのでHome.vueはそのまま使いたいような

**Comment by a-tak** [comment]
https://qiita.com/takatama/items/05e9fbc7199cde4caf60

これ参考に作り替えるか?

**Comment by a-tak** [comment]
画面準備中。
中に表示するSectionRowの開発が必要。
その前にSectionクラスが必要。

**Comment by a-tak** [comment]
画面での追加削除はできた。

* おそらくstoreにセクションは保持したがいい
* storeのcommitなどでfirebaseに書き込んだ方が自然

と思った。

storeをtypescriptでかけないのか?

**Comment by a-tak** [comment]
よくわからないながらstoreをTypeScriptで書いている。
今、TaskListMainのcommitを書き換えているところ。これ、逆に面倒じゃ無いか?

**Comment by a-tak** [comment]
理解できなかったのでやめた。ストアのタイプセーフ化はあきらめる。

**Comment by a-tak** [comment]
ストアのモジュール化したら
[2019-01-05T07:58:39.719Z]  @firebase/firestore: Firestore (5.5.9): INTERNAL UNHANDLED ERROR:  Error: FIRESTORE (5.5.9) INTERNAL ASSERTION FAILED: Updating a non-existent query
    at fail (http://localhost:8080/app.js:17600:11)
    at assert (http://localhost:8080/app.js:17608:9)
    at MemoryQueryCache../node_modules/@firebase/firestore/dist/index.cjs.js.MemoryQueryCache.updateQueryData (http://localhost:8080/app.js:30606:9)
    at http://localhost:8080/app.js:29978:56
    at forEachNumber (http://localhost:8080/app.js:17882:17)
    at http://localhost:8080/app.js:29942:13
    at MemoryPersistence../node_modules/@firebase/firestore/dist/index.cjs.js.MemoryPersistence.runTransaction (http://localhost:8080/app.js:30919:16)
    at LocalStore../node_modules/@firebase/firestore/dist/index.cjs.js.LocalStore.applyRemoteEvent (http://localhost:8080/app.js:29939:33)
    at SyncEngine../node_modules/@firebase/firestore/dist/index.cjs.js.SyncEngine.applyRemoteEvent (http://localhost:8080/app.js:33919:14)
    at RemoteStore../node_modules/@firebase/firestore/dist/index.cjs.js.RemoteStore.raiseWatchSnapshot (http://localhost:8080/app.js:32656:32)

**Comment by a-tak** [comment]
原因がエラーからわからないので、モジュール化した部分を手動で戻してエラーが解消するか試してみる。

**Comment by a-tak** [comment]
まだgetterやcommitでモジュールの指定が抜けているところがあっただけだった。で、なんでこのエラーなんだ。とりあえず直った。

**Comment by a-tak** [comment]
SectionRowからsectionがイベントで帰ってこないので調べているところ。
ここいければupdateTime undefinedが解決するはず

**Comment by a-tak** [comment]
セクションを保存するまでできたので、削除と表示を実装すれば設定画面は完了

**Comment by a-tak** [comment]
https://qiita.com/rubytomato@github/items/78087a2c69389f642760

 を元に参照貼ってリアル更新するやり方で実装している
